name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up and test with Python ${{ matrix.python-version }}
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        sudo apt-get install bats
        ./test
